baseurl = "https://mzaini30.com/"
title = "Zen"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "laptopzen" # Enable Disqus comments by entering your Disqus shortname
# googleAnalytics = "" # Enable Google Analytics by entering your tracking id

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[Author] # Used in authorbox
  name = "Zen"
  bio = "Penulis"
  avatar = "https://i.ibb.co/F0zbyrb/IMG-20200318-075012.jpg"

[Params]
  subtitle = "Blog Zen" # Subtitle of your site. Used in site header
  description = "Hanya sebuah blog random." # Site description. Used in meta description
  copyright = "Zen" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  twitter_cards = true # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["post", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "02-01-2006" # Change the format of dates
  mathjax = false # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  highlightColor = "#e22d30" # Override highlight color
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = true # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "mzaini30"
  # twitter = "mzaini30"
  # instagram = "mzaini30"
  # linkedin = "username"
  # telegram = "mzaini30a"
  # github = "mzaini30"
  # gitlab = "mzaini30"
  # bitbucket = "mzaini30"
  # email = "muhzaini30@gmail.com"

# Custom social links
[[Params.widgets.social.custom]]
  title = "Portofolio"
  url = "https://mzaini30.js.org"
  icon = "svg/instagram.svg" # Optional. Path relative to "layouts/partials"

# [[Params.widgets.social.custom]]
  # title = "My Home Page"
  # url = "http://example.com"

[outputs]
  home = ['html', 'rss', 'json']